[default]
app_name = "regen"
time_steps = 1_600_000  # Number of time steps to train the model
ticks_per_episode = 1_440  # at 1 tick per second, this means that an episode last 1 hour - window_size minutes aprox.
get_data_from_db = true
place_orders = false
db_name = "regen"

[development]
db_schema = "dev"
quote_asset = "BUSD"
db_type = "postgres"
bnb_base_urls = ["https://testnet.binance.vision"] # The base endpoint this client will send requests to.

[production]
db_type = "postgres"
bnb_base_urls = ["https://api.binance.com", "https://api1.binance.com", "https://api2.binance.com", "https://api3.binance.com"]